# Generated by Django 5.0.4 on 2024-05-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_car_delete_produnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_namr',
            new_name='car_name',
        ),
    ]
